version: '3.7'

services:
  redis:
    restart: always
    image: redis:latest
    networks:
      - backend
    hostname: redis
    ports:
      - "6379:6379"

  db-postgres:
    image: postgres:14.0-alpine
    env_file:
      - docker-compose.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend
    hostname: db-postgres

  api:
    image: ghcr.io/${REPO_NAME}:dev
    env_file:
      - docker-compose.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=redis
    command: sh /netomerch-backend/run.sh
    depends_on:
      - db-postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./static/:/static
    networks:
      - backend
    hostname: api

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend
    volumes:
      - ./static/:/static

networks:
  backend:
    name: backend

volumes:
  pg-data:
