version: '3.7'

services:
  redis:
    restart: always
    image: redis:latest
    networks:
      - backend
    hostname: redis

  db-postgres:
    image: postgres:14.0-alpine
    env_file:
      - docker-compose.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend
    hostname: db-postgres

  api:
    image: ghcr.io/${REPO_NAME}:dev
    env_file:
      - docker-compose.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    command: sh /netomerch-backend/run.sh
    depends_on:
      - db-postgres
      - redis
    expose:
      - 8000
    volumes:
      - static_volume:/srv/netomerch/backend/staticfiles
    networks:
      - backend
    hostname: api

  nginx:
    build: ../nginx
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - static_volume:/srv/netomerch/backend/staticfiles

networks:
  backend:
    name: backend

volumes:
  pg-data:
  static_volume:
