version: '3.7'

services:
  db-postgres:
    image: postgres:14.0-alpine
    env_file:
      - docker-compose.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend
    hostname: db-postgres-${MODE}

  api:
    image: ${REGISTRY}/${IMAGE_NAME}:${MODE}
    env_file:
      - docker-compose.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db-postgres-${MODE}
    command: sh /netomerch-backend/run.sh
    depends_on:
      - db-postgres
    networks:
      - backend
    hostname: api-${MODE}

networks:
  backend:
    name: backend
    external: true

volumes:
  pg-data:
