version: '3.7'

volumes:
  pgdata:

networks:
  private:
  proxy:
    external: true

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - private

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - private

  api:
    image: ${REGISTRY}/${IMAGE_NAME}:${MODE}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    networks:
      - private

  nginx:
    image: nginx:latest
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_HOST=${DOMAIN_NAME}
    depends_on:
      - api
    volumes:
      - ./static:/var/www/django/static:ro
      - ./media:/var/www/django/media:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    networks:
      - private
      - proxy
