version: '3.7'

services:
  redis:
    restart: always
    image: redis:latest
    hostname: redis

  db-postgres:
    image: postgres:14.0-alpine
    env_file:
      - docker-compose.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend
    hostname: db-postgres

  api:
    image: ${REGISTRY}/${IMAGE_NAME}:${MODE}
    env_file:
      - docker-compose.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=redis
    command: sh /netomerch-backend/run.sh
    depends_on:
      - db-postgres
      - redis
    volumes:
      - ./static/:/static
    hostname: api

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=dev.netomerch.tk
      - LETSENCRYPT_HOST=dev.netomerch.tk
    depends_on:
      - api
    volumes:
      - ./static/:/static

volumes:
  pg-data:
