version: '3.7'

services:
  redis:
    restart: always
    image: redis:latest
    hostname: redis
    networks:
      - backend


  db-postgres:
    image: postgres:14.0-alpine
    env_file:
      - docker-compose.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    hostname: db-postgres
    networks:
      - backend

  api:
    image: ${REGISTRY}/${IMAGE_NAME}:${MODE}
    env_file:
      - docker-compose.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    command: sh /netomerch-backend/run.sh
    depends_on:
      - db-postgres
      - redis
    volumes:
      - ./nginx/static/:/static
      - ./nginx/media/:/media
    hostname: api
    networks:
      - backend

  nginx:
    image: nginx:latest
    environment:
      - VIRTUAL_HOST=dev.netomerch.tk
      - LETSENCRYPT_HOST=dev.netomerch.tk
    depends_on:
      - api
    volumes:
      - ./nginx/static/:/usr/share/nginx/html/static
      - ./nginx/media/:/usr/share/nginx/html/media
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - backend
      - proxy

volumes:
  pg-data:

networks:
  proxy:
    external: true
  backend:
