name: ci

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mikeproalfamailru/netomerch-backend:latest

      - name: executing remote ssh commands restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.LOGIN }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/netomerch-backend
            sh down.sh
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/netomerch-backend:latest
            sh up.sh
