name: ci

on:
  pull_request:
    types: [ closed ]
    branches: [ dev ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:dev

      - name: Tar
        run: |
          cd ${{ github.workspace }}/deploy-dev
          tar -cf deploy-dev.tar *

      - name: Tar
        run: |
          cd ${{ github.workspace }}/nginx
          tar -cf nginx.tar *

      - name: upload docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "${{ github.workspace }}/deploy-dev/deploy-dev.tar"
          target: "/srv/netomerch/backend/"

      - name: upload nginx
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "${{ github.workspace }}/nginx/nginx.tar"
          target: "/srv/netomerch/backend/"

      - name: Connect via SSH, pull, restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export SECRET_KEY=$(echo $RANDOM | md5sum | head -c 20; echo;)
            export REPO_NAME=${{ github.repository }}
            cd /srv/netomerch/backend/
            mkdir -p deploy-dev
            chmod 777 deploy-dev
            mkdir -p nginx
            chmod 777 nginx
            tar -xvf /srv/netomerch/backend/github/workspace/deploy-dev/deploy-dev.tar -C deploy-dev
            tar -xvf /srv/netomerch/backend/github/workspace/nginx/nginx.tar -C nginx
            cd deploy-dev && chmod 666 *
            docker pull ghcr.io/${{ github.repository }}:dev
            docker-compose stop api
            docker-compose rm -f api
            docker-compose up -d
            rm -rf /srv/netomerch/backend/github
            for image in $(docker image ls| grep none|awk '{print $3}' | cat) ; do docker image rm "$image"; done
