name: demo-vars

on:
  push:
    branches: [ artrey-vars ]

jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
      - name: print        
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:fake
      
      - name: executing remote ssh commands restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /srv/netomerch/backend
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} > .env
